// Split the interface strings into one file per language.
//
//     node tools/i18n/build.mjs
//
// Evaluates app/i18n/strings.js as a browser would, so every merge and every
// fallback in it has already run, and writes what each language ends up with
// to app/static/js/i18n/<lang>.js. Then writes app/static/js/i18n/core.js:
// the list of those files, each with a hash of its contents so a changed
// language is never served from cache, followed by app/i18n/runtime.js.
//
// Fails, and writes nothing, if the split files would not rebuild exactly the
// tables the single file did.
//
// Copyright (C) 2025-2026 Ga Hing Woo (Jiaxing Hu)
// This file is part of EzySpeech, and is free software under the GNU Affero
// General Public License, version 3 or later. See LICENSE and TRADEMARK.md.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import vm from 'node:vm';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'app/static/js/i18n');

function evaluate(code) {
    const window = {};
    const ctx = { window, console,
        document: { addEventListener() {}, querySelectorAll() { return []; } },
        localStorage: { getItem() { return null; }, setItem() {} },
        navigator: { language: 'en' } };
    vm.createContext(ctx);
    vm.runInContext(code, ctx);
    return window;
}

const source = evaluate(readFileSync(join(ROOT, 'app/i18n/strings.js'), 'utf8'));
const strings = source.sharedI18n, status = source.sharedAiStatusLibrary;
const languages = Object.keys(strings);
assert.deepEqual(Object.keys(source).sort(), ['sharedAiStatusLibrary', 'sharedI18n'],
    'strings.js should define the two tables and nothing else');

const files = {};
const bodies = {};
for (const lang of languages) {
    const body = '/* Generated by tools/i18n/build.mjs from app/i18n/strings.js. Edit that. */\n'
        + `window.sharedI18n[${JSON.stringify(lang)}] = ${JSON.stringify(strings[lang])};\n`
        + (status[lang] ? `window.sharedAiStatusLibrary[${JSON.stringify(lang)}] = ${JSON.stringify(status[lang])};\n` : '');
    bodies[lang] = body;
    files[lang] = `${lang}.js?v=${createHash('sha256').update(body).digest('hex').slice(0, 8)}`;
}

// The split has to add up to what it replaces.
const rebuilt = evaluate('window.sharedI18n = {}; window.sharedAiStatusLibrary = {};\n'
    + languages.map(l => bodies[l]).join('\n'));
assert.deepEqual(JSON.parse(JSON.stringify(rebuilt.sharedI18n)), JSON.parse(JSON.stringify(strings)));
assert.deepEqual(JSON.parse(JSON.stringify(rebuilt.sharedAiStatusLibrary)), JSON.parse(JSON.stringify(status)));

mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) unlinkSync(join(OUT, f));
for (const lang of languages) writeFileSync(join(OUT, `${lang}.js`), bodies[lang]);
writeFileSync(join(OUT, 'core.js'),
    '/* Generated by tools/i18n/build.mjs from app/i18n/runtime.js. Edit that. */\n'
    + `window.EZY_I18N = ${JSON.stringify({ languages, files })};\n`
    + readFileSync(join(ROOT, 'app/i18n/runtime.js'), 'utf8'));

const kb = n => (n / 1024).toFixed(1) + 'KB';
const sizes = languages.map(l => Buffer.byteLength(bodies[l]));
console.log(`${languages.length} languages, ${kb(Math.min(...sizes))} to ${kb(Math.max(...sizes))} each; `
    + `core.js ${kb(readFileSync(join(OUT, 'core.js')).length)}`);
