#!/usr/bin/env python3
"""Generate app/templates/projection.html: the screen at the front of the room.

    python3 tools/patternfly/render_projection.py

The one surface in the app that leaves the shell — no masthead, no sidebar,
no scrollbar. It is read from the back of an auditorium, so the sizes are set
for distance rather than for a phone, and the page never scrolls: what does
not fit is what has already been said.

The markup follows tools/patternfly/design/markup/Projection.html; the classes
are in app/static/css/ezyspeech.css, which the design ships.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from render_user import ROOT                          # noqa: E402


def build():
    return '''<!DOCTYPE html>
<!-- Generated by tools/patternfly/render_projection.py. Edit that, not this. -->
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>EzySpeech - Projection</title>
  <link href="{{ static_url('patternfly/patternfly.css') }}" rel="stylesheet">
  <link href="{{ static_url('css/shell.css') }}" rel="stylesheet">
  <link href="{{ static_url('css/ezyspeech.css') }}" rel="stylesheet">
  <link href="{{ static_url('css/projection.css') }}" rel="stylesheet">
</head>

<body data-theme="light" data-page="projection">
  <div class="proj">
    <div class="proj-top">
      <span class="brand">
        <img class="pf-v6-c-brand brand-mark" src="{{ static_url('img/mabc-mark.png') }}"
             width="208" height="208" alt="">
        <span class="brand-name" id="projRoom">EzySpeech</span>
      </span>
      <span class="proj-top-end">
        <span class="proj-lang" id="projLang"></span>
        <span class="proj-clock" id="projClock">--:--:--</span>
      </span>
    </div>

    <!-- Two lines already said, then the line being said now. The room reads
         the big one; the two above it are there for anyone who looked away. -->
    <div class="proj-stage">
      <p class="proj-past proj-past-2" id="projPast2"></p>
      <p class="proj-past proj-past-1" id="projPast1"></p>
      <p class="proj-now" id="projNow"></p>
      <p class="proj-source" id="projSource"></p>
    </div>

    <!-- A verse, when one was read. Looked up in a Bible rather than
         translated, so it is exact and it says which Bible. -->
    <div class="proj-verse" id="projVerse" hidden>
      <p class="proj-verse-ref" id="projVerseRef"></p>
      <p class="proj-verse-text" id="projVerseText"></p>
    </div>

    <div class="proj-foot">
      <span class="proj-join" id="projJoin"></span>
      <span class="proj-langs" id="projLangs"></span>
    </div>
  </div>

  <script src="{{ static_url('js/i18n.js') }}"></script>
  <script src="{{ static_url('js/projection.js') }}"></script>
</body>

</html>
'''


if __name__ == "__main__":
    out = ROOT / "app/templates/projection.html"
    out.write_text(build(), encoding="utf-8")
    print("wrote %s (%d bytes)" % (out.relative_to(ROOT), out.stat().st_size))
